name: Saturne Update
on:
  push:
    branches:
      - deployment
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout deployment branch
        uses: actions/checkout@v4
        with:
          ref: deployment

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install Dependencies
        run: npm ci
        shell: bash

      - name: Build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build
        shell: bash

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install rsync on remote
        env:
          REMOTE_IP: ${{ secrets.REMOTE_IP }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
        run: ssh -o StrictHostKeyChecking=no -p 22 ${{ env.REMOTE_USER }}@${{ env.REMOTE_IP }} 'sudo apt-get update && sudo apt-get install -y rsync'
        shell: bash

      - name: Clean remote directory
        env:
          REMOTE_IP: ${{ secrets.REMOTE_IP }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
        run: ssh -o StrictHostKeyChecking=no -p 22 ${{ env.REMOTE_USER }}@${{ env.REMOTE_IP }} 'rm -rf /root/saturne/*'
        shell: bash

      - name: Upload via rsync
        env:
          REMOTE_IP: ${{ secrets.REMOTE_IP }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
        run: rsync -avz --delete .output/ ${{ env.REMOTE_USER }}@${{ env.REMOTE_IP }}:/root/saturne/
        shell: bash

      - name: Restart pm2
        env:
          REMOTE_IP: ${{ secrets.REMOTE_IP }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
        run: ssh -o StrictHostKeyChecking=no -p 22 ${{ env.REMOTE_USER }}@${{ env.REMOTE_IP }} 'source ~/.nvm/nvm.sh && ~/.nvm/versions/node/v22.3.0/bin/pm2 restart all'
        shell: bash
