name: Saturne Update
on:
  push:
    branches:
      - deployment
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout deployment branch
        uses: actions/checkout@v4
        with:
          ref: deployment

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 21.x

      - name: Install Dependencies
        run: npm ci
        shell: bash

      - name: Build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build
        shell: bash

      - name: Archive build
        run: |
          cd .output
          zip -r ../build.zip *
        shell: bash

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build.zip

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: Create Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          artifacts: build.zip
          name: Deployment ${{ github.run_id }}
          tag: deployment-${{ github.run_id }}
          token: ${{ secrets.TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: Extract build artifact
        run: unzip build.zip -d ./dist
        shell: bash

      - name: Clean remote directory
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass
          sshpass -p "hzS62wNC" ssh -o StrictHostKeyChecking=no -p 22 root@212.227.179.23 'rm -rf /root/saturne/*'
        shell: bash

      - name: Upload via rsync
        run: |
          rsync -avz --delete ./dist/ root@212.227.179.23:/root/saturne/
        env:
          RSYNC_RSH: 'sshpass -p hzS62wNC ssh -o StrictHostKeyChecking=no -p 22'
        shell: bash

      - name: Restart pm2
        run: |
          sshpass -p "hzS62wNC" ssh -o StrictHostKeyChecking=no -p 22 root@212.227.179.23 'source ~/.nvm/nvm.sh && ~/.nvm/versions/node/v21.6.1/bin/pm2 restart all'
        shell: bash

  cleanup:
    runs-on: ubuntu-latest
    needs: [ release, deploy ]

    steps:
      - name: Clear Artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: build
